// <auto-generated />
namespace HostMigrations.SqlServerLocalDb.PersistedGrant
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("HostMigrations.SqlServerLocalDb.Migrations.PersistedGrant.201804030135260_InitialCreate", typeof(InitialCreate).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "201804030135260_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
