version: 0.1.0.{build}
branches:
  only:
  - master
build_script:
- ps: .\build.ps1
test: on
services:
  - mssql2016           # start SQL Server 2016 Developer with SP1
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: rSX1FvecQW4t8xZKArs+1BWUOxHcPJOAClHP0YQopHtFHskqcudjd1foEFTSG4dh
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true

image: Visual Studio 2017

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/